"""initial

Revision ID: 0d1da68276f7
Revises: 
Create Date: 2022-05-03 10:52:11.462790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1da68276f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('album', sa.String(length=256), nullable=True),
    sa.Column('genre', sa.String(length=256), nullable=True),
    sa.Column('bit_rate', sa.SmallInteger(), nullable=True),
    sa.Column('duration', sa.SmallInteger(), nullable=True),
    sa.Column('file_size', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('song_id', name=op.f('pk__songs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
