"""add_md5

Revision ID: 5b1b57492b1a
Revises: 0eb76a0c8187
Create Date: 2022-05-15 18:03:46.954742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1b57492b1a'
down_revision = '0eb76a0c8187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('hash_', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'hash_')
    # ### end Alembic commands ###
