"""smallint to int

Revision ID: 6f2843aace8a
Revises: da4b36786fb3
Create Date: 2022-05-09 16:32:12.721294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2843aace8a'
down_revision = 'da4b36786fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
