"""bitrate to int

Revision ID: da4b36786fb3
Revises: 0d1da68276f7
Create Date: 2022-05-09 16:29:55.491557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4b36786fb3'
down_revision = '0d1da68276f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
